### ISSUE TITLE
Split off UDP syslog into separate system

### ISSUE THREAD

**Issue by stylewarning** [mmaul/cl-syslog#1]
It would be nice if the UDP functionality was split into a separate ASDF system so that things like USOCKET aren't loaded if they're not needed by a basic local syslog use.

Would require a version bump. `CL-SYSLOG` and `CL-SYSLOG.UDP` could both read from the same version file.

**Comment by mmaul** [comment]
As this would be a potentially breaking change. I think it might be better to create two systems cl-syslog.local and cl-syslog.udp then modify cl-syslog to depend on both systems. This way original conventions are inplace, but if you just want local syslog logging or just want udp syslog then you can just load the system you want. All systems can be defined in cl-syslog.asd so common version can be stored in a var in same.

**Comment by stylewarning** [comment]
I think that's a fine solution.
