### ISSUE TITLE
Does not build - sb-posix issue

### ISSUE THREAD

**Issue by xach** [mmaul/cl-syslog#9]
https://github.com/mmaul/cl-syslog/blob/b1b64102c2ee6eac04db61223d262539dec2574f/rfc5424.lisp#L653 introduces an implicit dependency on sb-posix that should be expressed in the system file. @tarballs-are-good

**Comment by mmaul** [comment]
Thx for heads up recently updated will fix.

**Comment by mmaul** [comment]
Fixed
